#!/usr/bin/env php
<?php declare(strict_types=1);

use Termage\Termage;
use Termage\Base\Screen;
use Termage\Base\Terminal;

require_once __DIR__ . '/vendor/autoload.php';

echo chr(27).chr(91).'H'.chr(27).chr(91).'J';

if (isset($argv[1])) {
    if ($argv[1] == 'div' && !isset($argv[2])) {
        echo (        
            Termage::div('TERMAGE')->font('block')->color('#41ff00')->colors('#41ff00', 'green')->pt2()->bg('#21183c')->textAlignCenter().
            Termage::div('Div')->font('chrome')->color('#41ff00')->pt1()->pb2()->bg('#21183c')->textAlignCenter()
        );
        echo Termage::hr()->color('#41ff00')->borderArrowDown()->bg('#21183c');
        echo (        
            Termage::div('Classes')->font('chrome')->color('#41ff00')->py2()->bg('#21183c')->textAlignCenter().
            Termage::div('m-{0-'.Terminal::getWidth().'} mx-{0-'.intval(Terminal::getWidth() / 2).'} | my-{0-'.intval(Terminal::getHeight() / 2).'} | mt-{0-'.Terminal::getHeight().'} | mb-{0-'.Terminal::getHeight() . '} | ml-{0-'.Terminal::getWidth().'} | mr-{0-'.Terminal::getWidth().'}')->bg('#21183c')->p(3)->px(10)->bold()->pt0()->pb1()->textAlignCenter()->color('#41ff00').
            Termage::div('p-{0-'.Terminal::getWidth().'} px-{0-'.intval(Terminal::getWidth() / 2).'} | py-{0-'.intval(Terminal::getHeight() / 2).'} | pt-{0-'.Terminal::getHeight().'} | pb-{0-'.Terminal::getHeight() . '} | pl-{0-'.Terminal::getWidth().'} | pr-{0-'.Terminal::getWidth().'}')->bg('#21183c')->p(3)->px(10)->bold()->pt0()->pb1()->textAlignCenter()->color('#41ff00').
            Termage::div('bg-{name} | color-{name} | d-{none,block,inline,inline-block}')->bg('#21183c')->p(3)->px(10)->bold()->pt0()->pb1()->textAlignCenter()->color('#41ff00').
            Termage::div('border-{square,rounded,double,heavy} | border-color-{name} | w-{0-'.Terminal::getWidth().'} | h-{0-'.Terminal::getWidth().'}')->bg('#21183c')->p(3)->px(10)->bold()->pt0()->pb1()->textAlignCenter()->color('#41ff00').
            Termage::div('bold | italic | underline | strikethrough | dim | blink | reverse | invisible')->bg('#21183c')->p(3)->px(10)->bold()->pt0()->pb1()->textAlignCenter()->color('#41ff00').
            Termage::div('text-align-{left,center,right} | text-vertical-align-{top,middle,bottom} | text-overflow-{clip,hidden,ellipsis}')->bg('#21183c')->p(3)->px(10)->bold()->pt0()->pb0()->textAlignCenter()->color('#41ff00').

            Termage::div('')->bg('#21183c')->p(3)->px(10)->bold()->pt0()->pb0()->textAlignCenter()->color('#41ff00')
        );
    } else {
        echo Termage::{$argv[1]}($argv[2] ?? 'Termage', $argv[3] ?? '')->render();
    }
} else {
    echo (        
        Termage::div('TERMAGE')->font('block')->color('#41ff00')->colors('#41ff00', 'green')->pt2()->bg('#21183c')->textAlignCenter().
        Termage::div('TOTALLY')->font('chrome')->color('#41ff00')->pt1()->bg('#21183c')->textAlignCenter().
        Termage::div('RAD TERMINAL STYLING FOR PHP')->font('chrome')->color('#41ff00')->pt1()->pb2()->bg('#21183c')->textAlignCenter().
        Termage::div('[u]Fluent[/u] and [u]incredible powerful[/u], object-oriented [u]interface[/u] for [u]customizing CLI[/u] output text color, background, formatting, theming and more!')->bg('#21183c')->p(3)->px(20)->bold()->pt0()->textAlignCenter()->color('#41ff00')
    );
    echo Termage::hr()->color('#41ff00')->borderArrowDown()->bg('#21183c');
    echo (        
        Termage::div('Elements')->font('chrome')->color('#41ff00')->py2()->bg('#21183c')->textAlignCenter().
        Termage::div('div | span | hr | chart | alert | paragraph | heading | anchor | bold | italic | strikethrough | underline')->bg('#21183c')->p(3)->px(10)->bold()->pt0()->textAlignCenter()->color('#41ff00')
    );
}